### ISSUE TITLE
pip install: confusing error when boost dependency is not found

### ISSUE THREAD

**Issue by o-smirnov** [casacore/python-casacore#134]
pip installing into a fresh virtualenv on 16.04, I get the following very misleading failure.

Careful perusing with @gijzelaerr revealed that some boost-dev or other was missing on the system, and ``sudo apt-get build-dep python-casacore`` solved the problem. So just a case of a very unhelpful error message!

```
$ pip install -U python-casacore
Collecting python-casacore
  Using cached python-casacore-2.2.1.tar.gz
Requirement not upgraded as not directly required: numpy in /home/ianh/venv/meerkat/lib/python2.7/site-packages (from python-casacore) (1.14.2)
Requirement not upgraded as not directly required: argparse in /usr/lib/python2.7 (from python-casacore) (1.2.1)
Building wheels for collected packages: python-casacore
  Running setup.py bdist_wheel for python-casacore ... error
  Complete output from command /home/ianh/venv/meerkat/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-N_gAgr/python-casacore/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-2AVudl --python-tag cp27:
  /tmp/pip-install-N_gAgr/python-casacore/setup.py:64: UserWarning: Could not find a boost library
    warnings.warn("Could not find a boost library")
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/pyrap
  copying pyrap/__init__.py -> build/lib.linux-x86_64-2.7/pyrap
  copying pyrap/quanta.py -> build/lib.linux-x86_64-2.7/pyrap
  copying pyrap/images.py -> build/lib.linux-x86_64-2.7/pyrap
  copying pyrap/tables.py -> build/lib.linux-x86_64-2.7/pyrap
  copying pyrap/measures.py -> build/lib.linux-x86_64-2.7/pyrap
  copying pyrap/fitting.py -> build/lib.linux-x86_64-2.7/pyrap
  copying pyrap/functionals.py -> build/lib.linux-x86_64-2.7/pyrap
  copying pyrap/util.py -> build/lib.linux-x86_64-2.7/pyrap
  creating build/lib.linux-x86_64-2.7/casacore
  copying casacore/__init__.py -> build/lib.linux-x86_64-2.7/casacore
  copying casacore/six.py -> build/lib.linux-x86_64-2.7/casacore
  creating build/lib.linux-x86_64-2.7/pyrap/images
  copying pyrap/images/__init__.py -> build/lib.linux-x86_64-2.7/pyrap/images
  copying pyrap/images/coordinates.py -> build/lib.linux-x86_64-2.7/pyrap/images
  copying pyrap/images/image.py -> build/lib.linux-x86_64-2.7/pyrap/images
  creating build/lib.linux-x86_64-2.7/casacore/measures
  copying casacore/measures/__init__.py -> build/lib.linux-x86_64-2.7/casacore/measures
  creating build/lib.linux-x86_64-2.7/casacore/fitting
  copying casacore/fitting/__init__.py -> build/lib.linux-x86_64-2.7/casacore/fitting
  copying casacore/fitting/fitting.py -> build/lib.linux-x86_64-2.7/casacore/fitting
  creating build/lib.linux-x86_64-2.7/casacore/quanta
  copying casacore/quanta/__init__.py -> build/lib.linux-x86_64-2.7/casacore/quanta
  copying casacore/quanta/quantity.py -> build/lib.linux-x86_64-2.7/casacore/quanta
  creating build/lib.linux-x86_64-2.7/casacore/functionals
  copying casacore/functionals/__init__.py -> build/lib.linux-x86_64-2.7/casacore/functionals
  copying casacore/functionals/functional.py -> build/lib.linux-x86_64-2.7/casacore/functionals
  creating build/lib.linux-x86_64-2.7/casacore/tables
  copying casacore/tables/table.py -> build/lib.linux-x86_64-2.7/casacore/tables
  copying casacore/tables/tablehelper.py -> build/lib.linux-x86_64-2.7/casacore/tables
  copying casacore/tables/__init__.py -> build/lib.linux-x86_64-2.7/casacore/tables
  copying casacore/tables/msutil.py -> build/lib.linux-x86_64-2.7/casacore/tables
  copying casacore/tables/tablecolumn.py -> build/lib.linux-x86_64-2.7/casacore/tables
  copying casacore/tables/wxtablebrowser.py -> build/lib.linux-x86_64-2.7/casacore/tables
  copying casacore/tables/tableindex.py -> build/lib.linux-x86_64-2.7/casacore/tables
  copying casacore/tables/tableutil.py -> build/lib.linux-x86_64-2.7/casacore/tables
  copying casacore/tables/tablerow.py -> build/lib.linux-x86_64-2.7/casacore/tables
  copying casacore/tables/tableiter.py -> build/lib.linux-x86_64-2.7/casacore/tables
  creating build/lib.linux-x86_64-2.7/casacore/util
  copying casacore/util/substitute.py -> build/lib.linux-x86_64-2.7/casacore/util
  copying casacore/util/__init__.py -> build/lib.linux-x86_64-2.7/casacore/util
  creating build/lib.linux-x86_64-2.7/casacore/images
  copying casacore/images/__init__.py -> build/lib.linux-x86_64-2.7/casacore/images
  copying casacore/images/coordinates.py -> build/lib.linux-x86_64-2.7/casacore/images
  copying casacore/images/image.py -> build/lib.linux-x86_64-2.7/casacore/images
  running build_ext
  building 'casacore.fitting._fitting' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/src
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/fit.cc -o build/temp.linux-x86_64-2.7/src/fit.o
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/fitting.cc -o build/temp.linux-x86_64-2.7/src/fitting.o
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-N_gAgr/python-casacore/setup.py", line 157, in <module>
      license='GPL')
    File "/home/ianh/venv/meerkat/local/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/ianh/venv/meerkat/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
      self.run_command(cmd_name)
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/ianh/venv/meerkat/local/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 78, in run
      _build_ext.run(self)
    File "/home/ianh/venv/meerkat/local/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "/usr/lib/python2.7/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/home/ianh/venv/meerkat/local/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
      self.build_extension(ext)
    File "/home/ianh/venv/meerkat/local/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 199, in build_extension
      _build_ext.build_extension(self, ext)
    File "/usr/lib/python2.7/distutils/command/build_ext.py", line 530, in build_extension
      target_lang=language)
    File "/usr/lib/python2.7/distutils/ccompiler.py", line 691, in link_shared_object
      extra_preargs, extra_postargs, build_temp, target_lang)
    File "/usr/lib/python2.7/distutils/unixccompiler.py", line 167, in link
      libraries)
    File "/usr/lib/python2.7/distutils/ccompiler.py", line 1085, in gen_lib_options
      lib_dir, lib_name = os.path.split(lib)
    File "/home/ianh/venv/meerkat/lib/python2.7/posixpath.py", line 85, in split
      i = p.rfind('/') + 1
  AttributeError: 'NoneType' object has no attribute 'rfind'
  
  ----------------------------------------
  Failed building wheel for python-casacore
  Running setup.py clean for python-casacore
Failed to build python-casacore
python-casacore 2.2.1 requires argparse, which is not installed.
Installing collected packages: python-casacore
  Running setup.py install for python-casacore ... error
    Complete output from command /home/ianh/venv/meerkat/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-N_gAgr/python-casacore/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-YZV11w/install-record.txt --single-version-externally-managed --compile --install-headers /home/ianh/venv/meerkat/include/site/python2.7/python-casacore:
    /tmp/pip-install-N_gAgr/python-casacore/setup.py:64: UserWarning: Could not find a boost library
      warnings.warn("Could not find a boost library")
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/pyrap
    copying pyrap/__init__.py -> build/lib.linux-x86_64-2.7/pyrap
    copying pyrap/quanta.py -> build/lib.linux-x86_64-2.7/pyrap
    copying pyrap/images.py -> build/lib.linux-x86_64-2.7/pyrap
    copying pyrap/tables.py -> build/lib.linux-x86_64-2.7/pyrap
    copying pyrap/measures.py -> build/lib.linux-x86_64-2.7/pyrap
    copying pyrap/fitting.py -> build/lib.linux-x86_64-2.7/pyrap
    copying pyrap/functionals.py -> build/lib.linux-x86_64-2.7/pyrap
    copying pyrap/util.py -> build/lib.linux-x86_64-2.7/pyrap
    creating build/lib.linux-x86_64-2.7/casacore
    copying casacore/__init__.py -> build/lib.linux-x86_64-2.7/casacore
    copying casacore/six.py -> build/lib.linux-x86_64-2.7/casacore
    creating build/lib.linux-x86_64-2.7/pyrap/images
    copying pyrap/images/__init__.py -> build/lib.linux-x86_64-2.7/pyrap/images
    copying pyrap/images/coordinates.py -> build/lib.linux-x86_64-2.7/pyrap/images
    copying pyrap/images/image.py -> build/lib.linux-x86_64-2.7/pyrap/images
    creating build/lib.linux-x86_64-2.7/casacore/measures
    copying casacore/measures/__init__.py -> build/lib.linux-x86_64-2.7/casacore/measures
    creating build/lib.linux-x86_64-2.7/casacore/fitting
    copying casacore/fitting/__init__.py -> build/lib.linux-x86_64-2.7/casacore/fitting
    copying casacore/fitting/fitting.py -> build/lib.linux-x86_64-2.7/casacore/fitting
    creating build/lib.linux-x86_64-2.7/casacore/quanta
    copying casacore/quanta/__init__.py -> build/lib.linux-x86_64-2.7/casacore/quanta
    copying casacore/quanta/quantity.py -> build/lib.linux-x86_64-2.7/casacore/quanta
    creating build/lib.linux-x86_64-2.7/casacore/functionals
    copying casacore/functionals/__init__.py -> build/lib.linux-x86_64-2.7/casacore/functionals
    copying casacore/functionals/functional.py -> build/lib.linux-x86_64-2.7/casacore/functionals
    creating build/lib.linux-x86_64-2.7/casacore/tables
    copying casacore/tables/table.py -> build/lib.linux-x86_64-2.7/casacore/tables
    copying casacore/tables/tablehelper.py -> build/lib.linux-x86_64-2.7/casacore/tables
    copying casacore/tables/__init__.py -> build/lib.linux-x86_64-2.7/casacore/tables
    copying casacore/tables/msutil.py -> build/lib.linux-x86_64-2.7/casacore/tables
    copying casacore/tables/tablecolumn.py -> build/lib.linux-x86_64-2.7/casacore/tables
    copying casacore/tables/wxtablebrowser.py -> build/lib.linux-x86_64-2.7/casacore/tables
    copying casacore/tables/tableindex.py -> build/lib.linux-x86_64-2.7/casacore/tables
    copying casacore/tables/tableutil.py -> build/lib.linux-x86_64-2.7/casacore/tables
    copying casacore/tables/tablerow.py -> build/lib.linux-x86_64-2.7/casacore/tables
    copying casacore/tables/tableiter.py -> build/lib.linux-x86_64-2.7/casacore/tables
    creating build/lib.linux-x86_64-2.7/casacore/util
    copying casacore/util/substitute.py -> build/lib.linux-x86_64-2.7/casacore/util
    copying casacore/util/__init__.py -> build/lib.linux-x86_64-2.7/casacore/util
    creating build/lib.linux-x86_64-2.7/casacore/images
    copying casacore/images/__init__.py -> build/lib.linux-x86_64-2.7/casacore/images
    copying casacore/images/coordinates.py -> build/lib.linux-x86_64-2.7/casacore/images
    copying casacore/images/image.py -> build/lib.linux-x86_64-2.7/casacore/images
    running build_ext
    building 'casacore.fitting._fitting' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/fit.cc -o build/temp.linux-x86_64-2.7/src/fit.o
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/fitting.cc -o build/temp.linux-x86_64-2.7/src/fitting.o
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-N_gAgr/python-casacore/setup.py", line 157, in <module>
        license='GPL')
      File "/home/ianh/venv/meerkat/local/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/ianh/venv/meerkat/local/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/ianh/venv/meerkat/local/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/ianh/venv/meerkat/local/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 78, in run
        _build_ext.run(self)
      File "/home/ianh/venv/meerkat/local/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/usr/lib/python2.7/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/home/ianh/venv/meerkat/local/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
        self.build_extension(ext)
      File "/home/ianh/venv/meerkat/local/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 199, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib/python2.7/distutils/command/build_ext.py", line 530, in build_extension
        target_lang=language)
      File "/usr/lib/python2.7/distutils/ccompiler.py", line 691, in link_shared_object
        extra_preargs, extra_postargs, build_temp, target_lang)
      File "/usr/lib/python2.7/distutils/unixccompiler.py", line 167, in link
        libraries)
      File "/usr/lib/python2.7/distutils/ccompiler.py", line 1085, in gen_lib_options
        lib_dir, lib_name = os.path.split(lib)
      File "/home/ianh/venv/meerkat/lib/python2.7/posixpath.py", line 85, in split
        i = p.rfind('/') + 1
    AttributeError: 'NoneType' object has no attribute 'rfind'
```

**Comment by gijzelaerr** [comment]
This has been solved a while ago https://github.com/casacore/python-casacore/commit/690cbfe7f0e021398ed7afc1e110c0ab37ece5a6
