### ISSUE TITLE
help installing on casacore developer box

### ISSUE THREAD

**Issue by dmehring** [casacore/python-casacore#139]
Apologies if this is not the appropriate forum for this question, but I have an RHEL workstation so cannot use apt-get to install. I have the casacore repos cloned in my user area for CASA development. Is it possible to configure pip to look for my casacore install in a nonstandard place? Currently it complains that it can't find the Converters files:
```
1430 dmehring@legolas:$ pip install --user python-casacore
Collecting python-casacore
...
   gcc -pthread -fno-strict-aliasing -g -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -DNDEBUG -g -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fPIC -I/opt/casa/02/include/python2.7 -c src/fit.cc -o build/temp.linux-x86_64-2.7/src/fit.o
    src/fit.cc:31:53: fatal error: casacore/python/Converters/PycBasicData.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/opt/casa/02/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-etzMXR/python-casacore/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-WPio7c-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-etzMXR/python-casacore/
```
Thanks

**Comment by tammojan** [comment]
As noted in README, try:
```
python setup.py build_ext -I/home/dmehring/opt/casacore/include -L/home/dmehring/opt/casacore/lib
python setup.py install --user
```

**Comment by dmehring** [comment]
Thanks for the quick response @tammojan . That gets me a bit farther, but I run into problems later:
```
1442 dmehring@legolas:$ python setup.py build_ext -I/export/data_1/dmehring/casa_eclipse/projects/master0/linux/include -L/export/data_1/dmehring/casa_eclipse/projects/master0/linux/lib
setup.py:64: UserWarning: Could not find a boost library
  warnings.warn("Could not find a boost library")
running build_ext
building 'casacore.fitting._fitting' extension
gcc -pthread -fno-strict-aliasing -g -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -DNDEBUG -g -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fPIC -I/export/data_1/dmehring/casa_eclipse/projects/master0/linux/include -I/opt/casa/02/include/python2.7 -c src/fit.cc -o build/temp.linux-x86_64-2.7/src/fit.o
gcc -pthread -fno-strict-aliasing -g -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -DNDEBUG -g -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fPIC -I/export/data_1/dmehring/casa_eclipse/projects/master0/linux/include -I/opt/casa/02/include/python2.7 -c src/fitting.cc -o build/temp.linux-x86_64-2.7/src/fitting.o
Traceback (most recent call last):
  File "setup.py", line 157, in <module>
    license='GPL')
  File "/opt/casa/02/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/opt/casa/02/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/opt/casa/02/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/opt/casa/02/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 75, in run
    _build_ext.run(self)
  File "/opt/casa/02/lib/python2.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/opt/casa/02/lib/python2.7/distutils/command/build_ext.py", line 448, in build_extensions
    self.build_extension(ext)
  File "/opt/casa/02/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/opt/casa/02/lib/python2.7/distutils/command/build_ext.py", line 530, in build_extension
    target_lang=language)
  File "/opt/casa/02/lib/python2.7/distutils/ccompiler.py", line 691, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/opt/casa/02/lib/python2.7/distutils/unixccompiler.py", line 162, in link
    libraries)
  File "/opt/casa/02/lib/python2.7/distutils/ccompiler.py", line 1085, in gen_lib_options
    lib_dir, lib_name = os.path.split(lib)
  File "/opt/casa/02/lib/python2.7/posixpath.py", line 85, in split
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
```

**Comment by tammojan** [comment]
Apparently setup.py cannot find the boost-python library. You could locate it using
```
ldd /export/data_1/dmehring/casa_eclipse/projects/master0/linux/lib/libcasa_python.so
```
Then you can add the path to boost-python in the `build_ext` command with:
```
python setup.py build_ext -L /export/data_1/dmehring/casa_eclipse/projects/master0/linux/lib/libcasa_python.so:/path/to/boost-pythonlib -I ...
```

**Comment by dmehring** [comment]
Thanks. By doing that, as well as some additional tweaks to include paths, I was able to build and install. And by making an addition to LD_LIBRARY_PATH to point to my casacore library install directory, I was able to run

from casacore import tables

successfully. So I appear to be good for now. Thanks for the quick help!

**Comment by tammojan** [comment]
Please also test successful installation with:
```
from casacore import tables as pt
t=pt.table()
```
Boost-python linking related problems are notorious for showing up at runtime..

**Comment by dmehring** [comment]
Looks good:

```
>>> from casacore import tables as pt
>>> t=pt.table("build_gcwrap/uid___A002_X86fcfa_X96c.mod.ms")
Successful readonly open of default-locked table build_gcwrap/uid___A002_X86fcfa_X96c.mod.ms: 23 columns, 65688 rows
```
