### ISSUE TITLE
handle unicode better

### ISSUE THREAD

**Issue by gijzelaerr** [casacore/python-casacore#158]
python-casacore often doesn't handle unicode strings properly, giving errors like this:
```
Exiting with exception: ArgumentError(Python argument types in  
    Table._getcol(table, unicode, int, int, int)                                                                         
did not match C++ signature:                                                                                             
    _getcol(casa::TableProxy {lvalue}, casa::String columnname, int startrow, int nrow, int rowincr))                    
 Traceback (most recent call last):                                                                                      
  File "/home/gijs/Work/CubiCal/cubical/main.py", line 356, in main                                                      
    chunks_per_tile=chunks_per_tile, max_chunks_per_tile=GD["dist"]["max-chunks"])                                       
  File "/home/gijs/Work/CubiCal/cubical/data_handler/ms_data_handler.py", line 863, in define_chunk                      
    value = self.fetch(column)                                                                                           
  File "/home/gijs/Work/CubiCal/cubical/data_handler/ms_data_handler.py", line 702, in fetch                             
    return (subset or self.data).getcol(colname, first_row, nrows)                                                       
  File "/home/gijs/Work/CubiCal/.venv2/local/lib/python2.7/site-packages/casacore/tables/table.py", line 1034, in getcol 
    return self._getcol(columnname, startrow, nrow, rowincr)                                                             
ArgumentError: Python argument types in                                                                                  
    Table._getcol(table, unicode, int, int, int)                                                                         
did not match C++ signature:                                                                                             
    _getcol(casa::TableProxy {lvalue}, casa::String columnname, int startrow, int nrow, int rowincr)

**Comment by gijzelaerr** [comment]
related to https://github.com/casacore/python-casacore/issues/138

I'm struggling to figure out how this actually works. It seems that casa has its own string type implementation. For python3 when a string is encoded it becomes a byte string type, while for python2 it is still a string.

I feel that is is going to be painful.

**Comment by gijzelaerr** [comment]
i guess this is causing the problems for py3
https://github.com/casacore/casacore/blame/master/python/Converters/PycBasicData.h#L103

**Comment by gijzelaerr** [comment]
merged!
