### ISSUE TITLE
pip install on windows fails (opt.split())

### ISSUE THREAD

**Issue by jjdmol** [casacore/python-casacore#228]
Trying to install python-casacore on windows runs into a bug in the argument parsing:
```
PS C:\temp\tango\tangostationcontrol> pip install python-casacore>=3.3.1
Collecting python-casacore>=3.3.1
  Using cached python-casacore-3.4.0.tar.gz (103 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\mol\AppData\Local\Temp\pip-install-8tzl0kvy\python-casacore_111c50aa4b7843c08cb03157e6a59e6f\setup.py", line 238, in <module>
          flag for flag in opt.split() if flag != '-Wstrict-prototypes'
      AttributeError: 'NoneType' object has no attribute 'split'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
PS C:\temp\tango\tangostationcontrol>
```

**Comment by tammojan** [comment]
Thanks for reporting. `python-casacore` is not supported on Windows. However, I appreciate your attempts. Have you managed to install casacore itself?

**Comment by jjdmol** [comment]
No I didn't try. This issue can then be closed I guess, leaving this as proof for the search queries of others.
