### ISSUE TITLE
Tests Failing

### ISSUE THREAD

**Issue by anchitjain1234** [casacore/python-casacore#51]
Tests fail when tested with ``master`` branch of ``casacore``.

Full trace:
```
======================================================================
ERROR: test_image (test_image.TestImage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/code/python-casacore/tests/test_image.py", line 14, in test_image
    im = image("", shape=[4, 3])
  File "/usr/local/lib/python2.7/dist-packages/python_casacore-2.1.0-py2.7-linux-x86_64.egg/casacore/images/image.py", line 178, in __init__
    maskname, tileshape, 0)
RuntimeError: IPosition::operator=(const IPosition&  - this and other differ in length

----------------------------------------------------------------------
```

**Comment by gijzelaerr** [comment]
This has been fixed in the casacore master branch and is included in the 2.1.0 release of casacore.
