### ISSUE TITLE
 pyrap.measures not correctly linked with casacore 2.2.0 in python-casacore 2.1.2

### ISSUE THREAD

**Issue by sjperkins** [casacore/python-casacore#73]
# casacore 2.2.0-2kern1 installed:

```bash
sperkins@simon-Y700:~$ apt show casacore-dev
Package: casacore-dev
Version: 2.2.0-2kern1
Priority: optional
Section: libdevel
Source: casacore
Maintainer: Debian Astronomy & Astrophysics Maintainers <debian-astro-maintainers@lists.alioth.debian.org>
Installed-Size: 12.9 MB
Depends: libcasa-casa2 (= 2.2.0-2kern1), libcasa-coordinates2 (= 2.2.0-2kern1), libcasa-derivedmscal2 (= 2.2.0-2kern1), libcasa-fits2 (= 2.2.0-2kern1), libcasa-images2 (= 2.2.0-2kern1), libcasa-lattices2 (= 2.2.0-2kern1), libcasa-meas2 (= 2.2.0-2kern1), libcasa-measures2 (= 2.2.0-2kern1), libcasa-mirlib2 (= 2.2.0-2kern1), libcasa-ms2 (= 2.2.0-2kern1), libcasa-msfits2 (= 2.2.0-2kern1), libcasa-python2 (= 2.2.0-2kern1), libcasa-scimath-f2 (= 2.2.0-2kern1), libcasa-scimath2 (= 2.2.0-2kern1), libcasa-tables2 (= 2.2.0-2kern1)
Download-Size: 1,522 kB
APT-Manual-Installed: yes
APT-Sources: http://ppa.launchpad.net/kernsuite/kern-dev/ubuntu xenial/main amd64 Packages
Description: CASA core library development files
 The casacore package contains the core libraries of the old
 AIPS++/CASA (Common Astronomy Software Applications) package. This
 split was made to get a better separation of core libraries and
 applications.
 .
 This package contains the files for application development.
```

# Create and activate a virtual environment

```bash
sperkins@simon-Y700:~$ virtualenv venv/pyrap
New python executable in /home/sperkins/venv/pyrap/bin/python
Installing setuptools, pip, wheel...done.
sperkins@simon-Y700:~$ source ~/venv/pyrap/bin/activate
(pyrap) sperkins@simon-Y700:~$ pip install python-casacore
Collecting python-casacore
Collecting numpy (from python-casacore)
  Using cached numpy-1.12.0-cp27-cp27mu-manylinux1_x86_64.whl
Requirement already satisfied: setuptools in ./venv/pyrap/lib/python2.7/site-packages (from python-casacore)
Requirement already satisfied: appdirs>=1.4.0 in ./venv/pyrap/lib/python2.7/site-packages (from setuptools->python-casacore)
Requirement already satisfied: packaging>=16.8 in ./venv/pyrap/lib/python2.7/site-packages (from setuptools->python-casacore)
Requirement already satisfied: six>=1.6.0 in ./venv/pyrap/lib/python2.7/site-packages (from setuptools->python-casacore)
Requirement already satisfied: pyparsing in ./venv/pyrap/lib/python2.7/site-packages (from packaging>=16.8->setuptools->python-casacore)
Installing collected packages: numpy, python-casacore
Successfully installed numpy-1.12.0 python-casacore-2.1.2
```

# Try to import `pyrap.measures`

```bash
(pyrap) sperkins@simon-Y700:~$ python -c 'import pyrap.measures'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/sperkins/venv/pyrap/local/lib/python2.7/site-packages/pyrap/measures.py", line 1, in <module>
    from casacore.measures import *
  File "/home/sperkins/venv/pyrap/local/lib/python2.7/site-packages/casacore/measures/__init__.py", line 30, in <module>
    import casacore.quanta as dq
  File "/home/sperkins/venv/pyrap/local/lib/python2.7/site-packages/casacore/quanta/__init__.py", line 1, in <module>
    from .quantity import quantity, is_quantity
  File "/home/sperkins/venv/pyrap/local/lib/python2.7/site-packages/casacore/quanta/quantity.py", line 2, in <module>
    from ._quanta import Quantity
ImportError: /home/sperkins/venv/pyrap/local/lib/python2.7/site-packages/casacore/quanta/_quanta.so: undefined symbol: _ZN4casa16throwArrayShapesEPKc
(pyrap) sperkins@simon-Y700:~$ 
```

**Comment by sjperkins** [comment]
This was caused by an obsolete pip cache entry
